name = "birhtday-gurl"
compatibility_date = "2026-02-26"
compatibility_flags = ["nodejs_compat"]

main = ".vercel/output/static/_worker.js/index.js"

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"